#!/bin/env bash
# mii bash init
# overrides the 'command not found' handler to automatically search for modules

# don't do anything unless this is a login shell
shopt -q login_shell || return

SRC_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MII_PREFIX=${SRC_DIR}/../../../
MII_BIN=${MII_PREFIX}/bin/mii

# need to export for common to use it
export MII_BIN

if [ ! -x "$MII_BIN" ]; then
    echo "[mii] couldn't find mii binary, please check it is built"
    return
fi

# run as bg job in a subshell, will stay quiet
($MII_BIN sync &)

if ! type module 2>&1 >/dev/null; then
    echo "[mii] module command not defined, will not autoload modules"
    return
fi

command_not_found_handle() {
    ${SRC_DIR}/common $@
}
