#!/bin/env zsh
# mii zsh init
# overrides the 'command not found' handler to automatically search for modules

SRC_DIR=$(dirname ${0:a})
MII_PREFIX=${SRC_DIR}/../../../
MII_BIN=${MII_PREFIX}/bin/mii

# stop on non-login shells
[[ -o login ]] || return

# need to export for common to use it
export MII_BIN

if [ ! -x "$MII_BIN" ]; then
    echo "[mii] couldn't find mii binary, please check it is built"
    return
fi

($MII_BIN sync &)

if ! type module 2>&1 >/dev/null; then
    echo "[mii] module command not defined, will not autoload modules"
    return
fi

command_not_found_handler() {
    # force bash-compatible word splitting
    setopt shwordsplit

    ${SRC_DIR}/common $@
}
