#!/bin/env zsh
# lmc zsh init
# overrides the 'command not found' handler to automatically search for modules

SRC_DIR=$(dirname ${0:a})
LMC_PREFIX=${SRC_DIR}/../../../

export PATH=${LMC_PREFIX}/bin:$PATH

if ! type lmc 2>&1 >/dev/null; then
    echo "[lmc] couldn't find lmc binary, please check it is built"
    return
fi

lmc build

if ! type module 2>&1 >/dev/null; then
    echo "[lmc] module command not defined, will not autoload modules"
    return
fi

command_not_found_handler() {
    # force bash-compatible word splitting
    setopt shwordsplit

    ${SRC_DIR}/common $@
}
